### ISSUE TITLE
Invalid channel name on iOS, android is OK

### ISSUE THREAD

**Issue by valebar** [heywhy/flutter-pusher-client#14]
Hi, I'm getting
`Error authorizing channel [private-user.114]: Optional("{\"status\":\"error\",\"code\":0,\"message\":\"Invalid channel name \",\"status_code\":500,\"exception\":\"Pusher\\\\PusherException\",\"file\":\"\\/var\\/www\\/xxxxxxx\\/html\\/vendor\\/pusher\\/pusher-php-server\\/src\\/Pusher.php\",\"line\":282,\"trace\":\"Pusher\\\\PusherException: Invalid channel name  in \\/var\\/www\\/xxxxxxx\\/html\\/vendor\\/pusher\\/pusher-php-server\\/src\\/Pusher.php:282\\nStack trace:\\n#0 \\/var\\/www\\/xxxxxxx\\/html\\/vendor\\/pusher\\/pusher-php-server\\/src\\/Pusher.php(729): Pusher\\\\Pusher->validate_channel(NULL)\\n#1 \\/var\\/www\\/xxxxx\\/html\\/vendor\\/pusher\\/pusher-php-server\\/src\\/Pusher.php(774): Pusher\\\\Pusher->socket_auth(NULL, NULL, \'{\\\"user_id\\\":114}\')\\n#2 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Broadcasting\\/Broadcasters\\/PusherBroadcaster.php(73): Pusher\\\\Pusher->presence_auth(NULL, NULL, 114, Array)\\n#3 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/beyondcode\\/laravel-websockets\\/src\\/Dashboard\\/Http\\/Controllers\\/AuthenticateDashboard.php(33): Illuminate\\\\Broadcasting\\\\Broadcasters\\\\PusherBroadcaster->validAuthenticationResponse(Object(Illuminate\\\\Http\\\\Request), Array)\\n#4 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/ControllerDispatcher.php(48): BeyondCode\\\\LaravelWebSockets\\\\Dashboard\\\\Http\\\\Controllers\\\\AuthenticateDashboard->__invoke(Object(Illuminate\\\\Http\\\\Request))\\n#5 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Route.php(219): Illuminate\\\\Routing\\\\ControllerDispatcher->dispatch(Object(Illuminate\\\\Routing\\\\Route), Object(BeyondCode\\\\LaravelWebSockets\\\\Dashboard\\\\Http\\\\Controllers\\\\AuthenticateDashboard), \'__invoke\')\\n#6 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Route.php(176): Illuminate\\\\Routing\\\\Route->runController()\\n#7 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(682): Illuminate\\\\Routing\\\\Route->run()\\n#8 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(30): Illuminate\\\\Routing\\\\Router->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#9 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Containers\\/Localization\\/Middlewares\\/LocalizationMiddleware.php(36): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#10 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Containers\\\\Localization\\\\Middlewares\\\\LocalizationMiddleware->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#11 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#12 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Ship\\/Middlewares\\/Http\\/ProfilerMiddleware.php(25): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#13 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Ship\\\\Middlewares\\\\Http\\\\ProfilerMiddleware->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#14 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#15 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Ship\\/Middlewares\\/Http\\/ProcessETagHeadersMiddleware.php(48): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#16 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Ship\\\\Middlewares\\\\Http\\\\ProcessETagHeadersMiddleware->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#17 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#18 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Middleware\\/SubstituteBindings.php(41): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#19 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Illuminate\\\\Routing\\\\Middleware\\\\SubstituteBindings->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#20 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#21 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Ship\\/Middlewares\\/Http\\/ValidateJsonContent.php(39): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#22 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Ship\\\\Middlewares\\\\Http\\\\ValidateJsonContent->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#23 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#24 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(104): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#25 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(684): Illuminate\\\\Pipeline\\\\Pipeline->then(Object(Closure))\\n#26 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(659): Illuminate\\\\Routing\\\\Router->runRouteWithinStack(Object(Illuminate\\\\Routing\\\\Route), Object(Illuminate\\\\Http\\\\Request))\\n#27 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(625): Illuminate\\\\Routing\\\\Router->runRoute(Object(Illuminate\\\\Http\\\\Request), Object(Illuminate\\\\Routing\\\\Route))\\n#28 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Router.php(614): Illuminate\\\\Routing\\\\Router->dispatchToRoute(Object(Illuminate\\\\Http\\\\Request))\\n#29 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Kernel.php(176): Illuminate\\\\Routing\\\\Router->dispatch(Object(Illuminate\\\\Http\\\\Request))\\n#30 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(30): Illuminate\\\\Foundation\\\\Http\\\\Kernel->Illuminate\\\\Foundation\\\\Http\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#31 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/barryvdh\\/laravel-debugbar\\/src\\/Middleware\\/InjectDebugbar.php(58): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#32 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Barryvdh\\\\Debugbar\\\\Middleware\\\\InjectDebugbar->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#33 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#34 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/barryvdh\\/laravel-cors\\/src\\/HandleCors.php(36): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#35 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Barryvdh\\\\Cors\\\\HandleCors->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#36 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#37 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Ship\\/Middlewares\\/Http\\/RequestMiddleware.php(27): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#38 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Ship\\\\Middlewares\\\\Http\\\\RequestMiddleware->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#39 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#40 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Ship\\/Middlewares\\/Http\\/RequestId.php(39): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#41 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Ship\\\\Middlewares\\\\Http\\\\RequestId->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#42 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#43 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/fideloper\\/proxy\\/src\\/TrustProxies.php(57): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#44 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Fideloper\\\\Proxy\\\\TrustProxies->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#45 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#46 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Middleware\\/TransformsRequest.php(31): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#47 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\TransformsRequest->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#48 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#49 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Middleware\\/TransformsRequest.php(31): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#50 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\TransformsRequest->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#51 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#52 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Middleware\\/ValidatePostSize.php(27): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#53 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\ValidatePostSize->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#54 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#55 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Middleware\\/CheckForMaintenanceMode.php(62): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#56 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): Illuminate\\\\Foundation\\\\Http\\\\Middleware\\\\CheckForMaintenanceMode->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#57 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#58 \\/var\\/www\\/xxxxxxxxx\\/html\\/app\\/Containers\\/Debugger\\/Middlewares\\/RequestsMonitorMiddleware.php(26): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#59 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(163): App\\\\Containers\\\\Debugger\\\\Middlewares\\\\RequestsMonitorMiddleware->handle(Object(Illuminate\\\\Http\\\\Request), Object(Closure))\\n#60 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Routing\\/Pipeline.php(53): Illuminate\\\\Pipeline\\\\Pipeline->Illuminate\\\\Pipeline\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#61 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Pipeline\\/Pipeline.php(104): Illuminate\\\\Routing\\\\Pipeline->Illuminate\\\\Routing\\\\{closure}(Object(Illuminate\\\\Http\\\\Request))\\n#62 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Kernel.php(151): Illuminate\\\\Pipeline\\\\Pipeline->then(Object(Closure))\\n#63 \\/var\\/www\\/xxxxxxxxx\\/html\\/vendor\\/laravel\\/framework\\/src\\/Illuminate\\/Foundation\\/Http\\/Kernel.php(116): Illuminate\\\\Foundation\\\\Http\\\\Kernel->sendRequestThroughRouter(Object(Illuminate\\\\Http\\\\Request))\\n#64 \\/var\\/www\\/xxxxxxxxx\\/html\\/public\\/index.php(53): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))\\n#65 {main}\"}")` as http response from my Laravel Echo server. I'm using laravel-websockets pusher server. It works fine on android, so it's not a server error.

**Comment by valebar** [comment]
ok, I found out what the problem was. Apparently iOS doesn't like it if you add 'Accept': 'application/json' header to PusherAuth headers.
